export const DIMENSIONS = {
  CANVAS_WIDTH: 500,
  CANVAS_HEIGHT: 700,
};

export const PLAYER = {
  WIDTH: 80,
  HEIGHT: 80,
  START_X: DIMENSIONS.CANVAS_WIDTH / 2 - 40,
  START_Y: DIMENSIONS.CANVAS_HEIGHT - 80,
  GRAVITY: 0.2,
  JUMP_STRENGTH: -7,
  MOVE_SPEED: 2,
};

export const PLATFORM = {
  WIDTH: 100,
  HEIGHT: 40,
  START_Y: 550,
  MIN_DISTANCE: 30,
  MAX_DISTANCE: 60,
};
