import { Tile } from "../models/Tile";
import { DIMENSIONS } from "../constants";
import laneImage from "../assets/car-lane.png";

export const tiles = [
  new Tile(
    DIMENSIONS.LANE_HORIZONTAL_DISTANCE,
    DIMENSIONS.LANE_VERTICAL_DISTANCE,
    DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_HEIGHT,
    laneImage
  ),
  new Tile(
    DIMENSIONS.LANE_HORIZONTAL_DISTANCE * 2 + DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_VERTICAL_DISTANCE,
    DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_HEIGHT,
    laneImage
  ),
  new Tile(
    DIMENSIONS.LANE_HORIZONTAL_DISTANCE,
    DIMENSIONS.LANE_VERTICAL_DISTANCE * 2 + DIMENSIONS.LANE_HEIGHT,
    DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_HEIGHT,
    laneImage
  ),
  new Tile(
    DIMENSIONS.LANE_HORIZONTAL_DISTANCE * 2 + DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_VERTICAL_DISTANCE * 2 + DIMENSIONS.LANE_HEIGHT,
    DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_HEIGHT,
    laneImage
  ),
  new Tile(
    DIMENSIONS.LANE_HORIZONTAL_DISTANCE,
    DIMENSIONS.LANE_VERTICAL_DISTANCE * 4 + DIMENSIONS.LANE_HEIGHT,
    DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_HEIGHT,
    laneImage
  ),
  new Tile(
    DIMENSIONS.LANE_HORIZONTAL_DISTANCE * 2 + DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_VERTICAL_DISTANCE * 4 + DIMENSIONS.LANE_HEIGHT,
    DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_HEIGHT,
    laneImage
  ),
  new Tile(
    DIMENSIONS.LANE_HORIZONTAL_DISTANCE,
    DIMENSIONS.LANE_VERTICAL_DISTANCE * 6 + DIMENSIONS.LANE_HEIGHT,
    DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_HEIGHT,
    laneImage
  ),
  new Tile(
    DIMENSIONS.LANE_HORIZONTAL_DISTANCE * 2 + DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_VERTICAL_DISTANCE * 6 + DIMENSIONS.LANE_HEIGHT,
    DIMENSIONS.LANE_WIDTH,
    DIMENSIONS.LANE_HEIGHT,
    laneImage
  ),
];
