export const DIMENSIONS = {
  CANVAS_WIDTH: 500,
  CANVAS_HEIGHT: 800,
  CAR_WIDTH: 100,
  CAR_HEIGHT: 80,
  LANE_WIDTH: 20,
  LANE_HEIGHT: 100,
  LANE_VERTICAL_DISTANCE: 100,
  LANE_HORIZONTAL_DISTANCE: 150,
};

export const SPEED = 5;
